name: plstzi_trips_app
description: My first proyect

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  generic_bloc_provider: ^2.1.1

  cupertino_icons: ^1.0.2
  firebase_core: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: "Lato"
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf